"""
Prepare a gmx_MMPBSA calculation (https://github.com/Valdes-Tresanca-MS/gmx_MMPBSA).

* **Protein-only system.** Implicit solvent needs no explicit water, and a solvated
  system of 1–2 M atoms does not fit a typical WSL/laptop memory. ``complex.tpr`` is
  cut from the canonical run input with ``gmx convert-tpr`` (Protein group),
  ``complex.top`` keeps only the solute molecule types, ``complex.ndx`` has exactly
  two groups (0 = receptor, 1 = ligand) built from the persisted chain identity, and
  the trajectory is the validated, PBC-treated solute trajectory. No Amber
  ``forcefields=`` line: parameters come from the GROMACS topology.
* **Ionic strength derived** from the ions in the run input and the box volume
  (never an unrecorded 0.150 M).
* **Explicit decomposition residues**: every residue that came within 6 Å of the
  partner in *any* frame (``print_res = "within 6"`` is evaluated on the first frame
  only and silently drops residues that bind later).
* **Run script with a probe gate**: ~11 frames of GB first; production runs only if
  every bonded Δ term is exactly zero (single-trajectory consistency) and the
  decomposition covers the requested residues (else it falls back to all residues).
"""

from __future__ import annotations

import json
import os
import re
import shutil
from pathlib import Path

AVOGADRO = 6.02214076e23
CHARGE = {"POT": 1, "K": 1, "K+": 1, "NA": 1, "SOD": 1, "NA+": 1, "LI": 1, "RB": 1, "CS": 1,
          "CLA": -1, "CL": -1, "CL-": -1, "BR": -1, "IOD": -1, "I": -1, "F": -1,
          "MG": 2, "MG2": 2, "CAL": 2, "CA": 2, "CA2": 2, "ZN": 2, "ZN2": 2, "MN": 2,
          "FE2": 2, "FE3": 3, "CU": 2, "CO": 2, "NI": 2, "CD": 2}
SOLVENT = {"SOL", "WAT", "HOH", "TIP3", "TIP4", "TIP5", "TIP3P", "SPC", "SPCE", "T3P", "T4P",
           "OPC", "TP3"}


def derive_ionic_strength(ion_counts: dict[str, int], volume_nm3: float) -> dict:
    """I = ½ Σ cᵢ zᵢ² with cᵢ = nᵢ / (N_A V). Also the 1:1 salt concentration (minority ion)."""
    litres = volume_nm3 * 1e-24
    terms, pos, neg = [], 0, 0
    for name, n in ion_counts.items():
        z = CHARGE.get(name.upper())
        if z is None:
            continue
        c = n / (AVOGADRO * litres)
        terms.append((name, n, z, c))
        pos += n if z > 0 else 0
        neg += n if z < 0 else 0
    ionic = 0.5 * sum(c * z * z for _, _, z, c in terms)
    salt = min(pos, neg) / (AVOGADRO * litres) if terms else 0.0
    return {"ionic_strength_M": round(ionic, 4), "salt_1to1_M": round(salt, 4),
            "volume_nm3": volume_nm3, "ions": {n: k for n, k, _, _ in terms},
            "note": "counts from the run input, volume of the first solute-trajectory frame; "
                    "the box includes the solute, so this slightly underestimates the "
                    "bulk concentration"}


def complex_topology(top_text: str, keep: list[str]) -> str:
    """Replace the ``[ molecules ]`` section with the kept molecule types (count 1 each, in order)."""
    m = re.search(r"^\s*\[\s*molecules\s*\]\s*$", top_text, re.M | re.I)
    if not m:
        raise ValueError("topology has no [ molecules ] section")
    head = top_text[:m.end()]
    body = "\n; Compound\t#mols\n" + "".join(f"{k}\t1\n" for k in keep)
    return head + body


def solute_molecules(top_text: str) -> list[str]:
    """Molecule types of ``[ molecules ]`` that are not solvent or ions, in order."""
    m = re.search(r"^\s*\[\s*molecules\s*\]\s*$(.*)", top_text, re.M | re.I | re.S)
    out = []
    for line in (m.group(1) if m else "").splitlines():
        line = line.split(";")[0].strip()
        if not line or line.startswith("["):
            continue
        name, *count = line.split()
        if name.upper() in SOLVENT or name.upper() in CHARGE:
            continue
        out.extend([name] * int(count[0] if count else 1))
    return out


def ranges(numbers: list[int]) -> str:
    """[1,2,3,7,9,10] -> '1-3,7,9-10'."""
    nums = sorted(set(int(n) for n in numbers))
    out, start = [], None
    for i, n in enumerate(nums):
        if start is None:
            start = n
        if i + 1 == len(nums) or nums[i + 1] != n + 1:
            out.append(f"{start}" if start == n else f"{start}-{n}")
            start = None
    return ",".join(out)


def input_files(temperature: float, ionic: float, start: int, end: int, interval: int,
                print_res: str, sys_name: str = "complex") -> tuple[str, str]:
    """(mmgbsa.in, mmpbsa.in) -- GB and PB run separately because PBRadii is global."""
    gb = f"""MM-GBSA generated by MolDynX Tools (gmx_MMPBSA)
&general
  sys_name            = "{sys_name}_GB",
  startframe          = {start},
  endframe            = {end},
  interval            = {interval},
  temperature         = {temperature},
  PBRadii             = 3,
  interaction_entropy = 1,
  ie_segment          = 25,
  c2_entropy          = 1,
  verbose             = 2,
/
&gb
  igb                 = 5,
  saltcon             = {ionic:.4f},
/
&decomp
  idecomp             = 2,
  dec_verbose         = 3,
  print_res           = "{print_res}",
/
"""
    pb = f"""MM-PBSA generated by MolDynX Tools (gmx_MMPBSA)
&general
  sys_name            = "{sys_name}_PB",
  startframe          = {start},
  endframe            = {end},
  interval            = {interval},
  temperature         = {temperature},
  PBRadii             = 7,
  verbose             = 2,
/
&pb
  istrng              = {ionic:.4f},
  fillratio           = 4.0,
  inp                 = 1,
/
"""
    return gb, pb


RUN_SCRIPT = r"""#!/usr/bin/env bash
# gmx_MMPBSA (https://github.com/Valdes-Tresanca-MS/gmx_MMPBSA) -- generated by MolDynX Tools.
# probe gate (GB, ~11 frames) -> GB with decomposition -> PB. Run from this folder.
set -uo pipefail
ENV_NAME="${MOLDYNX_MMPBSA_ENV:-gmxMMPBSA}"
source "$(conda info --base 2>/dev/null)/etc/profile.d/conda.sh" 2>/dev/null && conda activate "$ENV_NAME"
export OMP_NUM_THREADS=1 OMPI_MCA_btl_vader_single_copy_mechanism=none
CORES=$(( $(nproc) / __SMT__ )); [ "$CORES" -lt 1 ] && CORES=1
FREE_GB=$(awk '/MemAvailable/{printf "%d", $2/1048576}' /proc/meminfo)
PB_RANKS=$(( FREE_GB * 10 / 35 )); [ "$PB_RANKS" -gt "$CORES" ] && PB_RANKS=$CORES; [ "$PB_RANKS" -lt 1 ] && PB_RANKS=1
LOG=run.log; stamp(){ echo "[$(date '+%F %T')] $*" | tee -a "$LOG"; }
COMMON="-cs complex.tpr -ci complex.ndx -cg 0 1 -ct complex.xtc -cp complex.top"

stamp "probe: GB on 11 frames"
mkdir -p probe && sed -E 's/^( *endframe *= *).*/\1__PROBE_END__,/' mmgbsa.in > probe/probe.in
( cd probe && ln -sf ../complex.* ../toppar . && gmx_MMPBSA -O -nogui -i probe.in $COMMON \
    -o R.dat -eo R.csv -do D.dat -deo D.csv > run.log 2>&1 ); rc=$?
python3 check_probe.py probe/R.csv probe/D.csv requested_residues.json | tee -a "$LOG"; gate=$?
if [ $rc -ne 0 ] || [ $gate -eq 3 ]; then stamp "PROBE FAILED (exit $rc, gate $gate) -- not running production"; exit 3; fi
if [ $gate -eq 2 ]; then stamp "decomposition did not cover the requested residues -> print_res = all"
  sed -i -E 's/^( *print_res *= *).*/\1"all",/' mmgbsa.in; fi

stamp "GB: $CORES MPI ranks"
mkdir -p gb && ( cd gb && ln -sf ../complex.* ../toppar . && cp ../mmgbsa.in . && \
  mpirun -np $CORES --bind-to none gmx_MMPBSA -O -nogui -i mmgbsa.in $COMMON \
    -o FINAL_RESULTS_MMGBSA.dat -eo FINAL_RESULTS_MMGBSA.csv \
    -do FINAL_DECOMP_MMGBSA.dat -deo FINAL_DECOMP_MMGBSA.csv > run.log 2>&1 ); stamp "GB exit $?"
stamp "PB: $PB_RANKS MPI ranks (~3.3 GB per rank)"
mkdir -p pb && ( cd pb && ln -sf ../complex.* ../toppar . && cp ../mmpbsa.in . && \
  mpirun -np $PB_RANKS --bind-to none gmx_MMPBSA -O -nogui -i mmpbsa.in $COMMON \
    -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv > run.log 2>&1 ); stamp "PB exit $?"
"""

CHECK_PROBE = r'''"""Probe gate: exit 3 = inconsistent (bonded delta != 0 or no total), 2 = decomposition incomplete."""
import csv, io, json, sys
res_csv, dec_csv, req_json = sys.argv[1:4]
lines = open(res_csv, encoding="utf-8").read().splitlines()
i = next(k for k, l in enumerate(lines) if l.startswith("Delta Energy Terms"))
rows = list(csv.DictReader(io.StringIO("\n".join(l for l in lines[i + 1:] if l))))
bonded = ["BOND", "ANGLE", "DIHED", "UB", "IMP", "CMAP", "1-4 VDW", "1-4 EEL"]
bad = [f"{b}={r[b]}" for r in rows for b in bonded if b in r and abs(float(r[b])) > 1e-6]
if bad or not rows or "TOTAL" not in rows[0]:
    print("probe: bonded delta terms are not zero:", bad[:5]); sys.exit(3)
print(f"probe: {len(rows)} frames, bonded deltas all zero, dTOTAL {rows[0]['TOTAL']}")
want = json.load(open(req_json))
seen = set()
for l in open(dec_csv, encoding="utf-8"):
    p = l.split(",")
    if len(p) > 2 and p[1][:3] in ("R::", "L::"):
        seen.add(p[1].split("::")[0] + ":" + p[1].rsplit(":", 1)[1])
missing = [w for w in want if w not in seen]
print(f"probe: decomposition covers {len(want) - len(missing)} of {len(want)} requested residues")
sys.exit(2 if missing else 0)
'''


def write_package(out_dir: Path, *, tpr_src: Path, top_text: str, toppar_src: Path | None,
                  solute_xtc: Path, receptor: dict, ligand: dict, temperature: float,
                  ionic: dict, frames: dict, print_res_local: dict, meta: dict) -> dict:
    """
    Write everything except ``complex.tpr`` (made with GROMACS by :func:`make_complex_tpr`).

    receptor / ligand : {"name", "letter", "atom_start1", "atom_stop1"} -- 1-based, inclusive
        atom ranges in the solute trajectory; ``letter`` is the chain letter of the partner
        in topology order (gmx_MMPBSA ``print_res`` syntax).
    print_res_local : {"R": [local residue numbers], "L": [...]} numbered from 1 per partner.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    keep = solute_molecules(top_text)
    (out_dir / "complex.top").write_text(complex_topology(top_text, keep), encoding="utf-8")
    if toppar_src and toppar_src.is_dir():
        shutil.copytree(toppar_src, out_dir / "toppar", dirs_exist_ok=True)
    with open(out_dir / "complex.ndx", "w", newline="\n") as fh:
        for g in (receptor, ligand):
            ids = list(range(g["atom_start1"], g["atom_stop1"] + 1))
            fh.write(f"[ {re.sub(r'[^A-Za-z0-9_]', '_', g['name'])} ]\n")
            for k in range(0, len(ids), 15):
                fh.write(" ".join(f"{i:6d}" for i in ids[k:k + 15]) + "\n")
    shutil.copyfile(solute_xtc, out_dir / "complex.xtc")
    parts = []
    for side, g in (("R", receptor), ("L", ligand)):
        if print_res_local.get(side):
            parts.append(f"{g['letter']}/{ranges(print_res_local[side])}")
    # no interface residue set available -> decompose everything ("within 6" would be
    # evaluated on the first frame only and miss residues that bind later)
    print_res = " ".join(parts) if parts else "all"
    gb, pb = input_files(temperature, ionic["ionic_strength_M"], frames["start"], frames["end"],
                         frames["interval"], print_res)
    (out_dir / "mmgbsa.in").write_text(gb, encoding="utf-8")
    (out_dir / "mmpbsa.in").write_text(pb, encoding="utf-8")
    probe_end = frames["start"] + 10 * frames["interval"]
    smt = 2 if (os.cpu_count() or 2) > 1 else 1
    (out_dir / "run_mmpbsa.sh").write_text(
        RUN_SCRIPT.replace("__PROBE_END__", str(probe_end)).replace("__SMT__", str(smt)),
        encoding="utf-8", newline="\n")
    (out_dir / "check_probe.py").write_text(CHECK_PROBE, encoding="utf-8", newline="\n")
    requested = [f"{s}:{n}" for s, ns in print_res_local.items() for n in ns]
    (out_dir / "requested_residues.json").write_text(json.dumps(requested), encoding="utf-8")
    info = {**meta, "receptor": receptor, "ligand": ligand, "solute_molecules": keep,
            "temperature_K": temperature, "ionic": ionic, "frames": frames,
            "print_res": print_res, "tpr_source": str(tpr_src),
            "gmx_mmpbsa": "https://github.com/Valdes-Tresanca-MS/gmx_MMPBSA"}
    (out_dir / "prepare_meta.json").write_text(json.dumps(info, indent=2, default=str),
                                               encoding="utf-8")
    return info


def make_complex_tpr(gmx, tpr_src: Path, out_dir: Path) -> tuple[bool, str]:
    """``gmx make_ndx`` (default groups) + ``gmx convert-tpr`` on the Protein group."""
    from moldynx.io.gromacs import run_gmx
    ndx = out_dir / "default.ndx"
    r = run_gmx(gmx, ["make_ndx", "-f", str(tpr_src), "-o", str(ndx)], stdin="q\n")
    if r.returncode != 0 or not ndx.exists():
        return False, "gmx make_ndx failed: " + (r.stderr or "")[-300:]
    names = re.findall(r"^\[\s*(.+?)\s*\]", ndx.read_text(), re.M)
    if "Protein" not in names:
        return False, "no 'Protein' group in the default index"
    r = run_gmx(gmx, ["convert-tpr", "-s", str(tpr_src), "-n", str(ndx),
                      "-o", str(out_dir / "complex.tpr")], stdin=f"{names.index('Protein')}\n")
    ok = r.returncode == 0 and (out_dir / "complex.tpr").exists()
    return ok, "" if ok else "gmx convert-tpr failed: " + (r.stderr or "")[-300:]
